// Generated by gencpp from file edvarka/log.msg
// DO NOT EDIT!


#ifndef EDVARKA_MESSAGE_LOG_H
#define EDVARKA_MESSAGE_LOG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edvarka
{
template <class ContainerAllocator>
struct log_
{
  typedef log_<ContainerAllocator> Type;

  log_()
    {
    }
  log_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::edvarka::log_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edvarka::log_<ContainerAllocator> const> ConstPtr;

}; // struct log_

typedef ::edvarka::log_<std::allocator<void> > log;

typedef boost::shared_ptr< ::edvarka::log > logPtr;
typedef boost::shared_ptr< ::edvarka::log const> logConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edvarka::log_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edvarka::log_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace edvarka

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edvarka::log_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edvarka::log_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edvarka::log_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edvarka::log_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edvarka::log_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edvarka::log_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edvarka::log_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::edvarka::log_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::edvarka::log_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edvarka/log";
  }

  static const char* value(const ::edvarka::log_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edvarka::log_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::edvarka::log_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edvarka::log_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct log_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edvarka::log_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::edvarka::log_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // EDVARKA_MESSAGE_LOG_H
